// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartParking.Infrastructure;

#nullable disable

namespace SmartParking.Infrastructure.Migrations
{
    [DbContext(typeof(SmartParkingDbContext))]
    [Migration("20260126120359_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartParking.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SensorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "SensorCode")
                        .IsUnique();

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("LastDistanceCm")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("LastUpdateAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("OccupiedThresholdCm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(15.0);

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.HasIndex("SensorId")
                        .IsUnique()
                        .HasFilter("[SensorId] IS NOT NULL");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.TelemetryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("DeviceTs")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("DistanceCm")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SensorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SlotLabel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StatusAfter")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCode");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("SlotLabel");

                    b.ToTable("TelemetryLogs");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.Device", "Device")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Slot", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.Sensor", "Sensor")
                        .WithOne("Slot")
                        .HasForeignKey("SmartParking.Domain.Entities.Slot", "SensorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Device", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Slot");
                });
#pragma warning restore 612, 618
        }
    }
}
